""".\crear modelos v2

Revision ID: 8a5552e417bd
Revises: f6dd1d0e1b30
Create Date: 2022-06-30 19:28:09.042780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5552e417bd'
down_revision = 'f6dd1d0e1b30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('municipio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'municipio')
    # ### end Alembic commands ###
